#!/bin/sh

#outputdir=output

#if [ $# -gt 0 ];
#then
outputdir="$1";
dims="$2";
#fi
# create output directory if it does not exist
if test ! -d $outputdir;
  then mkdir $outputdir;
fi
# copy parameter (".data") files to output directory
if test -f input2D.data; then
   morefiles=input2D.data;
else
   morefiles="";
fi
# put the makefile in the output directory, since
# we use it to select what modules are used
if test -f Makefile; then
   morefiles="Makefile $morefiles";
fi
cp $morefiles $outputdir;
# copy information sufficient to reconstruct the
# code used to generate the data
#\eg parents > $outputdir/hg_parents
#\eg diff > $outputdir/hg_diff

