function plotmesh2(outputdir_in)

global outputdir
if(nargin<1)
  outputdir='mesh_output';
else
  outputdir=outputdir_in;
end

% TITLE INFO --------------------------------------------------------------
disp(' ')
disp('  2D UNSTRUCTURED GRID PLOTTING ROUTINE')
disp(' ')
% END TITLE INFO ----------------------------------------------------------

disp(' Loading grid data: please wait ...');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% READ-IN MESH INFO %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fids = fopen([outputdir '/mesh_params.dat'],'r');
if fids==-1
  disp(' ');
  error(['File  ',outputdir,'/mesh_params.dat  not found.']);
end
NumElems = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumPhysElems = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumGhostElems = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumNodes = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumPhysNodes = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumBndNodes = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
NumEdges = fscanf(fids,'%d',1);  fscanf(fids,'%s',1); fscanf(fids,'%s',1);
fclose(fids);

fids = fopen([outputdir '/mesh_tnode.dat'],'r');
tmp = fscanf(fids,'%d %d %d',[3,inf]);
fclose(fids);
tnode = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_node.dat'],'r');
tmp = fscanf(fids,'%e',[2,inf]);
fclose(fids);
node = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_bnd_node.dat'],'r');
tmp = fscanf(fids,'%d',[1,inf]);
fclose(fids);
bnd = transpose(tmp);
clear tmp;
for i=1:length(bnd)
  bnd_node(i,1:2) = node(bnd(i),1:2);
end

fids = fopen([outputdir '/mesh_ghost_link.dat'],'r');
tmp = fscanf(fids,'%d',[1,inf]);
fclose(fids);
ghost_link = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_area_prim.dat'],'r');
tmp = fscanf(fids,'%e',[1,inf]);
fclose(fids);
area_prim = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_area_dual.dat'],'r');
tmp = fscanf(fids,'%e',[1,inf]);
fclose(fids);
area_dual = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_edge.dat'],'r');
tmp = fscanf(fids,'%e %e %e %e',[4,inf]);
fclose(fids);
edge = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_tedge.dat'],'r');
tmp = fscanf(fids,'%d %d %d',[3,inf]);
fclose(fids);
tedge = transpose(tmp);
clear tmp;

fids = fopen([outputdir '/mesh_eelem.dat'],'r');
tmp = fscanf(fids,'%d %d',[2,inf]);
fclose(fids);
eelem = transpose(tmp);
clear tmp;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

disp(' Finished loading grid data.');
disp(' ');

xmin = min(node(:,1));
ymin = min(node(:,2));
xmax = max(node(:,1));
ymax = max(node(:,2));

xtmp = 0.01*(xmax-xmin);
ytmp = 0.01*(ymax-ymin);

xmin = xmin - xtmp;
xmax = xmax + xtmp;

ymin = ymin - ytmp;
ymax = ymax + ytmp;


figure(1);
clf;
ztri=trisurf(tnode(1:NumPhysElems,:),node(1:NumPhysNodes,1),node(1:NumPhysNodes,2),...
             zeros(size(node(1:NumPhysNodes,1)))); 
colormap('jet');
axis on; box on; grid off;
axis('equal');
axis([xmin xmax ymin ymax]);
set(gca,'fontsize',14);
t1 = title('Mesh Generated by MeshGenC++');
set(t1,'fontsize',14);
set(gca,'plotboxaspectratio',[1 1 1]);
hold on;
plot(bnd_node(:,1),bnd_node(:,2),'ro');
hold off;

figure(2);
clf;
ztri=trisurf(tnode(1:NumElems,:),node(1:NumNodes,1),node(1:NumNodes,2),...
             zeros(size(node(1:NumNodes,1)))); 
colormap('jet');
axis on; box on; grid off;
axis('equal');
axis([xmin xmax ymin ymax]);
set(gca,'fontsize',14);
t1 = title('Mesh with Ghost Elements');
set(t1,'fontsize',14);
set(gca,'plotboxaspectratio',[1 1 1]);
hold on;
plot(bnd_node(:,1),bnd_node(:,2),'ro');
hold off;

figure(1)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  CALL EXTRA FUNCTION, SPECIFIED BY USER
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plot_extra
