all: qhull meshgencpp

qhull:
	cd qhull && make
meshgencpp:
	cd meshgencpp && make
clean: cleanqhull cleanmeshgencpp

cleanqhull:
	cd qhull && make clean
cleanmeshgencpp:
	cd meshgencpp && make clean
